name: Vue
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install --dev
      - name: Lint
        run: yarn run lint
      - name: Test
        run: yarn run test
      - name: Build
        run: yarn run build
      - name: Deploy to Netlify
        uses: South-Paw/action-netlify-deploy@v1.0.4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_API_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './dist'
